---
- name: Automatizacion apagado servidores con apache
  hosts: Apache
  become: True
  tasks:
    - name: Apagado servicio tomcat
      service: name=tomcat state=stopped enabled=true
      notify: shutdown_machine
      
  handlers:
    - name: shutdown_machine
      shell: shutdown -r 
